GAZEBO_CAMERA_TOPIC = "/camera"

ZMQ_CAMERA_ENDPOINT = "ipc://bt_app.camera"
ZMQ_CAMERA_TOPIC = b"camera.image"
ZMQ_TRACKER_RESULT_ENDPOINT = "ipc://bt_app.tracker_result"
ZMQ_TRACKER_RESULT_TOPIC = b"tracker_result"

DEFAULT_CAMERA_WINDOW = "Gazebo Camera"
DEFAULT_RED_BOX_TRACKER_WINDOW = "Red Box Tracker"

CAMERA_HORIZONTAL_FOV_RAD = 1.047

__all__ = [
    "CAMERA_HORIZONTAL_FOV_RAD",
    "DEFAULT_CAMERA_WINDOW",
    "DEFAULT_RED_BOX_TRACKER_WINDOW",
    "GAZEBO_CAMERA_TOPIC",
    "ZMQ_CAMERA_ENDPOINT",
    "ZMQ_CAMERA_TOPIC",
    "ZMQ_TRACKER_RESULT_ENDPOINT",
    "ZMQ_TRACKER_RESULT_TOPIC",
]
